2020-11-06 10:49:58,685 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/projects/demo/myapp/views.py", line 49, in post
    u = User.objects.get(email=email)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
myapp.models.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 59, in post
    return render(request, self.template_name, {'msg': mjessage})
NameError: name 'mjessage' is not defined
2020-11-06 11:01:07,429 [ERROR]- Internal Server Error: /registration
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/avanik/projects/demo/myapp/decorator.py", line 7, in wrap
    return view_func(request, args, *kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
TypeError: post() takes 2 positional arguments but 3 were given
2020-11-06 11:01:34,882 [ERROR]- Internal Server Error: /registration
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/avanik/projects/demo/myapp/decorator.py", line 7, in wrap
    return view_func(request, args, *kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
TypeError: post() takes 2 positional arguments but 3 were given
2020-11-06 11:06:09,508 [WARNING]- Not Found: /login/
2020-11-06 11:06:13,546 [WARNING]- Not Found: /login/
2020-11-06 11:19:14,512 [ERROR]- Internal Server Error: /logout
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 67, in logout
    print("===after===", request.session['user_login'])
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-06 11:31:27,820 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'in', expected 'endblock'. Did you forget to register or load this tag?
2020-11-06 12:36:10,055 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "request.session['user_login']"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 955, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 888, in __init__
    super().__init__(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 891, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['user_login']' from 'request.session['user_login']'
2020-11-06 12:42:52,688 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 46, in get
    del request.session['user_login']
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 62, in __delitem__
    del self._session[key]
KeyError: 'user_login'
2020-11-06 12:43:03,739 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 46, in get
    del request.session['user_login']
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 62, in __delitem__
    del self._session[key]
KeyError: 'user_login'
2020-11-06 12:48:18,229 [ERROR]- Internal Server Error: /logout
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 78, in logout
    del request.session['user_login']
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 62, in __delitem__
    del self._session[key]
KeyError: 'user_login'
2020-11-06 12:48:39,201 [ERROR]- Internal Server Error: /logout
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 78, in logout
    del request.session['user_login']
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 62, in __delitem__
    del self._session[key]
KeyError: 'user_login'
2020-11-06 12:49:41,268 [ERROR]- Internal Server Error: /logout
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 78, in logout
    del request.session['user_login']
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 62, in __delitem__
    del self._session[key]
KeyError: 'user_login'
2020-11-06 12:53:53,173 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 21, in get
    print('===',request.session["user_login"])
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-06 12:53:54,524 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 21, in get
    print('===',request.session["user_login"])
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-06 12:54:21,059 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 20, in get
    if request.session["user_login"]:
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-06 12:54:22,231 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 20, in get
    if request.session["user_login"]:
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-06 12:56:38,385 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 54, in get
    print('===',request.session["user_login"])
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-06 12:58:21,813 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 61, in post
    if request.session["user_login"]:
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'user_login'
2020-11-09 03:47:40,864 [WARNING]- Not Found: /favicon.ico
2020-11-09 05:22:38,940 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 81, in save
    obj = self.create_model_instance(data)
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 68, in create_model_instance
    session_data=self.encode(data),
  File "/home/avanik/env/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 96, in encode
    serialized = self.serializer().dumps(session_dict)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/signing.py", line 87, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
2020-11-09 06:41:51,380 [ERROR]- Internal Server Error: /login
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 63, in get
    return render(request, self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/avanik/env/lib/python3.6/site-packages/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/avanik/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registration' not found. 'registration' is not a valid view function or pattern name.

2020-11-09 07:29:00,579 [WARNING]- Not Found: /login/
2020-11-09 07:29:02,253 [WARNING]- Not Found: /login/
2020-11-09 07:29:06,145 [WARNING]- Not Found: /login/
2020-11-09 07:30:28,015 [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/avanik/env/lib/python3.6/site-packages/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/avanik/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registration' not found. 'registration' is not a valid view function or pattern name.
2020-11-10 03:50:06,533 [WARNING]- Not Found: /favicon.ico
2020-11-10 06:04:26,145 [WARNING]- Not Found: /favicon.ico
2020-11-10 08:46:52,660 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=email)
NameError: name 'email' is not defined
2020-11-10 08:48:54,804 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=email)
NameError: name 'email' is not defined
2020-11-10 08:49:09,584 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=email)
NameError: name 'email' is not defined
2020-11-10 08:49:13,570 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=email)
NameError: name 'email' is not defined
2020-11-10 08:49:13,829 [WARNING]- Not Found: /favicon.ico
2020-11-10 08:51:45,581 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=usession.email)
AttributeError: 'dict' object has no attribute 'email'
2020-11-10 08:52:05,314 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email = 'usession.email')
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
myapp.models.DoesNotExist: User matching query does not exist.
2020-11-10 08:53:35,480 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=email)
NameError: name 'email' is not defined
2020-11-10 08:53:39,371 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 92, in get
    udata = User.objects.get(email=email)
NameError: name 'email' is not defined

2020-11-10 09:04:51,916 [WARNING]- Not Found: /index.html
2020-11-10 09:04:52,970 [WARNING]- Not Found: /index.html
2020-11-10 09:04:55,075 [WARNING]- Not Found: /index.html
2020-11-10 09:05:11,781 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myapp.views.Editprofile didn't return an HttpResponse object. It returned None instead.
2020-11-10 09:09:01,080 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 93, in get
    return get
NameError: name 'get' is not defined2020-11-10 09:44:17,196 [ERROR]- Internal Server Error: /editprofile
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myapp.views.Editprofile didn't return an HttpResponse object. It returned None instead.
2020-11-10 10:45:59,011 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myapp.views.Home didn't return an HttpResponse object. It returned None instead.
2020-11-10 11:05:58,348 [WARNING]- Not Found: /favicon.ico
2020-11-11 04:57:55,785 [ERROR]- Internal Server Error: /edituser
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 103, in post
    self.request.User.save()
AttributeError: 'WSGIRequest' object has no attribute 'User'

2020-11-11 06:45:49,013 [WARNING]- Not Found: /favicon.ico
2020-11-11 06:46:42,181 [WARNING]- Not Found: /favicon.ico
2020-11-11 07:03:14,930 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 21, in get
    return render(request, self.template_name, {'user': u})
  File "/home/avanik/env/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 229, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'js' appears more than once
2020-11-11 07:03:15,938 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 21, in get
    return render(request, self.template_name, {'user': u})
  File "/home/avanik/env/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 229, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'js' appears more than once
2020-11-11 09:40:45,833 [ERROR]- Internal Server Error: /2/
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
TypeError: patch() got an unexpected keyword argument 'id'
2020-11-11 09:44:06,725 [WARNING]- Not Found: /2/
2020-11-11 09:50:22,722 [ERROR]- Internal Server Error: /edituser/2
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
TypeError: patch() got an unexpected keyword argument 'id'
2020-11-23 06:32:56,885 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 21, in get
    user = User.objects.get(email=u['email'])
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
myapp.models.DoesNotExist: User matching query does not exist.
2020-11-23 06:33:35,870 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 21, in get
    user = User.objects.get(email=u['email'])
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
myapp.models.DoesNotExist: User matching query does not exist.
2020-11-23 07:00:33,540 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 22, in get
    company.objects.all()
NameError: name 'company' is not defined
2020-11-23 07:00:33,939 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 22, in get
    company.objects.all()
NameError: name 'company' is not defined
2020-11-23 07:00:34,305 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 22, in get
    company.objects.all()
NameError: name 'company' is not defined
2020-11-23 09:28:15,658 [ERROR]- Internal Server Error: /listcompany
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/avanik/env/lib/python3.6/site-packages/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/avanik/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'deletecompany' not found. 'deletecompany' is not a valid view function or pattern name.2020-11-24 08:49:17,145 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '+1' from 'count+1'
2020-11-24 11:21:39,737 [WARNING]- Not Found: /favicon.ico
2020-11-24 11:24:16,815 [WARNING]- Not Found: /favicon.ico
2020-11-24 12:03:33,697 [WARNING]- Not Found: /favicon.ico
2020-11-24 12:07:05,851 [WARNING]- Not Found: /favicon.ico
2020-11-24 12:11:40,589 [WARNING]- Not Found: /favicon.ico
2020-11-24 12:22:26,706 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 517, in render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 676, in resolve
    obj = self.var.resolve(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 802, in resolve
    value = self._resolve_lookup(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 864, in _resolve_lookup
    current = current()
  File "/home/avanik/projects/demo/myapp/models.py", line 56, in hobby_list
    strtolist = json.loads(self.hobby.replace("'", '"'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-11-24 13:04:14,588 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 517, in render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 676, in resolve
    obj = self.var.resolve(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 802, in resolve
    value = self._resolve_lookup(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 864, in _resolve_lookup
    current = current()
  File "/home/avanik/projects/demo/myapp/models.py", line 53, in hobby_list
    strtolist = json.loads(self.hobby.replace("'", '"'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-11-24 14:08:48,604 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 150, in get
    context = self.get_context_data(**kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 196, in get_context_data
    Company.objects.get(company_id)
NameError: name 'company_id' is not defined
2020-11-24 14:09:03,900 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 150, in get
    context = self.get_context_data(**kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 196, in get_context_data
    Company.objects.get(id=company_id)
NameError: name 'company_id' is not defined
2020-11-24 14:11:40,413 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(c_name).get(employee.company_id)' from 'Company.objects.values(c_name).get(employee.company_id)'
2020-11-24 14:12:08,263 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('c_name').get(employee.company_id)' from 'Company.objects.values('c_name').get(employee.company_id)'
2020-11-24 14:23:41,595 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
2020-11-24 14:29:59,297 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/home/avanik/env/lib/python3.6/site-packages/django/middleware/common.py", line 113, in process_response
    if response.status_code == 404:
AttributeError: 'dict' object has no attribute 'status_code'
2020-11-24 16:13:03,315 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 150, in get
    context = self.get_context_data(**kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 196, in get_context_data
    Company.objects.get(id='company_id')
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'company_id'
2020-11-24 16:13:18,467 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 150, in get
    context = self.get_context_data(**kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 196, in get_context_data
    Company.objects.get(id)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1150, in build_filter
    arg, value = filter_expr
TypeError: 'builtin_function_or_method' object is not iterable
2020-11-25 03:55:47,765 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/projects/demo/myapp/views.py", line 215, in post
    u.save()
  File "/home/avanik/projects/demo/myapp/models.py", line 50, in save
    super().full_clean()
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/base.py", line 1166, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'name': ['This field cannot be blank.'], 'username': ['This field cannot be blank.'], 'email': ['This field cannot be blank.'], 'gender': ['This field cannot be null.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 219, in post
    print(type(e[0]))
TypeError: 'ValidationError' object does not support indexing
2020-11-25 04:04:27,341 [WARNING]- Not Found: /favicon.ico
2020-11-25 04:20:43,120 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '{{employee.company_id}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 955, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 888, in __init__
    super().__init__(*args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 891, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{employee.company_id}}' from '{{employee.company_id}}'
2020-11-25 04:22:52,345 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/avanik/projects/demo/myapp/views.py", line 215, in post
    u.save()
  File "/home/avanik/projects/demo/myapp/models.py", line 50, in save
    super().full_clean()
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/base.py", line 1144, in full_clean
    self.clean_fields(exclude=exclude)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/base.py", line 1186, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 607, in clean
    self.validate(value, model_instance)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/fields/related.py", line 902, in validate
    **{self.remote_field.field_name: value}
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/avanik/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'test2'
2020-11-25 04:38:35,823 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 976, in do_if
    raise TemplateSyntaxError('Malformed template tag at line {0}: "{1}"'.format(token.lineno, token.contents))
django.template.exceptions.TemplateSyntaxError: Malformed template tag at line 28: "else request.session.user_login and request.session.user_data.is_admin"
2020-11-25 04:38:36,863 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 976, in do_if
    raise TemplateSyntaxError('Malformed template tag at line {0}: "{1}"'.format(token.lineno, token.contents))
django.template.exceptions.TemplateSyntaxError: Malformed template tag at line 28: "else request.session.user_login and request.session.user_data.is_admin"
2020-11-25 04:38:54,607 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 976, in do_if
    raise TemplateSyntaxError('Malformed template tag at line {0}: "{1}"'.format(token.lineno, token.contents))
django.template.exceptions.TemplateSyntaxError: Malformed template tag at line 28: "else request.session.user_login and request.session.user_data.is_admin"
2020-11-25 04:39:10,618 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 488, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 549, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 25: 'if'. Looking for one of: elif, else, endif.
2020-11-25 04:59:36,917 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 105: 'set', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2020-11-25 05:03:23,266 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|++:"1"' from 'count|++:"1"'
2020-11-25 05:08:08,109 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '+1' from 'count+1'
2020-11-25 05:12:28,131 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=count+1' from 'count=count+1'
2020-11-25 05:19:26,815 [ERROR]- Internal Server Error: /listemployee
Traceback (most recent call last):
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/avanik/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 1477, in do_with
    nodelist = parser.parse(('endwith',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 454, in parse
    raise self.error(token, e)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/home/avanik/env/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=count+1' from 'count=count+1'
